### ISSUE TITLE
503 Service Temporarily Unavailable - nginx

### ISSUE THREAD

**Issue by Richi2293** [chriszarate/docker-compose-wordpress#10]
Hi,

I'm trying this docker compose but always return me this error on localhost:

![image](https://user-images.githubusercontent.com/5848941/37566066-6a559348-2ab4-11e8-8600-3e1a6b3ba11c.png)

I'm on macOS 10.12.6
I followed the instructions in "Set up".

This is my docker-compose file: ('plugin-folder' is my plugin file)

```
version: "2"

services:
  wordpress:
    image: "chriszarate/wordpress:4.9.1"
    environment:
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN}"
      WORDPRESS_ACTIVATE_PLUGINS: "plugin-folder" # plugin folder relative to /wp-content/plugins/
      WORDPRESS_ACTIVATE_THEME: ""   # theme folder relative to /wp-content/themes/
      WORDPRESS_SITE_TITLE: "Project"
      WORDPRESS_SITE_URL: "http://${DOCKER_DEV_DOMAIN}"
      # XDEBUG_CONFIG: "remote_host=${DOCKER_LOCAL_IP} idekey=xdebug"
    depends_on:
      - "mysql"
    networks:
      - "front"
      - "back"
    volumes:
      - "../plugin-folder:/var/www/html/wp-content/plugins/plugin-folder"
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"
  proxy:
    image: "jwilder/nginx-proxy:alpine"
    ports:
      - "80:80"
    networks:
      front:
        aliases:
          - "${DOCKER_DEV_DOMAIN}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

networks:
  front: {}
  back: {}
```

This is my .env file:

```
DOCKER_DEV_DOMAIN=project.test
DOCKER_LOCAL_IP=192.168.1.73
```

These are the logs of the proxy container:
![image](https://user-images.githubusercontent.com/5848941/37566148-3389b76c-2ab5-11e8-85df-a99b3b04a444.png)

These are the logs of the wordpress container:
![image](https://user-images.githubusercontent.com/5848941/37566153-4dba90de-2ab5-11e8-8106-b304a3e7c52e.png)
