### ISSUE TITLE
Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php'

### ISSUE THREAD

**Issue by MikeiLL** [chriszarate/docker-compose-wordpress#2]
Hello again, dear Chris.

```
Fatal error: require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/mz-mindbody-api/tests/bootstrap.php on line 14
```
I think `/tmp` is empty.

Working with this tree:
```
├── README.md
├── bin
│   └── install-wp-tests.sh
├── docker-compose.yml
├── inc
│   ├── stuff.php
├── languages
├── lib
│   ├── stuff.php
├── my-great-plugin.php
├── package.json
├── phpcs.ruleset.xml
├── phpunit.xml.dist
├── tests
│   ├── bootstrap.php
│   └── test-sample.php
```
After cycling docker-compose up and down and back up, with `.env`:
```
DOCKER_DEV_DOMAIN=great.dev
DOCKER_LOCAL_IP=108.205.63.107
PHPUNIT_TEST_DIR=my-great-plugin
```
Seems:
```
docker-compose exec wordpress ls /tmp
sess_000bd338f45070de2efeb6b050b75be6  
sess_5b2da936132835ee0c05214a2fb05b62
```

No `wordpress-tests-lib`

Hmmm.
```
PHPUNIT_TEST_DIR: "/var/www/html/wp-content/plugins/my-great-plugin"
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN}"
      WORDPRESS_ACTIVATE_PLUGINS: "my-great-plugin" # dot dot dot
    volumes:
      - ".:/var/www/html/wp-content/plugins/my-great-plugin"
```
Tried with your scaffold and running `docker-compose exec wordpress wp scaffold plugin-tests  my-great-plugin`.

Am I missing something again?

The VIP wrapper is working at least further than I have gotten with this one so far. Thanks a lot for your help, man. I will surely pass the wisdom on.
