### ISSUE TITLE
Can't connect to project.dev Port 80

### ISSUE THREAD

**Issue by cstromquist** [chriszarate/docker-compose-wordpress#5]
Hi Chris,

Great repo. But am having an issue with connecting to my project.dev link. I followed the docs and have project.dev in /etc/hosts. But when I spin up Docker, I keep getting a 503 Service Unavailable error. Would you happen to know why I get that?

I'm trying to use Guzzle to connect as a client to test my REST API, but my url doesn't appear to be working.

**Here's my .env:**
```
DOCKER_DEV_DOMAIN=project.dev
DOCKER_LOCAL_IP=172.29.32.21
PHPUNIT_TEST_DIR=my-plugin
```

**docker-compose.yml:**

```
version: "2"

services:
  wordpress:
    image: "chriszarate/wordpress:4.7.2"
    environment:
      PHPUNIT_TEST_DIR: "/var/www/html/wp-content/plugins/my-plugin"
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN}"
      WORDPRESS_ACTIVATE_PLUGINS: "my-plugin" # plugin folder relative to /wp-content/plugins/
      WORDPRESS_ACTIVATE_THEME: ""   # theme folder relative to /wp-content/themes/
      WORDPRESS_SITE_TITLE: "My Plugin"
      XDEBUG_CONFIG: "remote_host=${DOCKER_LOCAL_IP} idekey=xdebug"
    depends_on:
      - "mysql"
    networks:
      - "front"
      - "back"
    volumes:
      - ".:/var/www/html/wp-content/plugins/my-plugin"
  mysql:
    image: "mariadb"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"
  mysql_phpunit:
    image: "mariadb"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress_phpunit"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"
  proxy:
    image: "jwilder/nginx-proxy"
    ports:
      - "8082:80"
    networks:
      front:
        aliases:
          - "${DOCKER_DEV_DOMAIN}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

networks:
  front: {}
  back: {}
```

Thank you,
Chris
