### ISSUE TITLE
503 Service Temporarily Unavailable nginx/1.13.8

### ISSUE THREAD

**Issue by MikeiLL** [chriszarate/docker-compose-wordpress#9]
Sorry for the spam. Nginx isn't loading the site, I think following generating the phpunit scaffold, but I had also pulled in latest changes from this repository.

When I `docker-compose exec proxy bash`, there doesn't seem to be any content in `/var/log/nginx/access.log` or `error.log`.

The `docker-compose log proxy` contains:

```
proxy_1      | nginx.1    | mzmbo.dev 172.20.0.1 - - [02/Feb/2018:15:23:48 +0000] "GET / HTTP/1.1" 503 213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1      | forego     | starting dockergen.1 on port 5000
proxy_1      | forego     | starting nginx.1 on port 5100
proxy_1      | dockergen.1 | 2018/02/03 22:56:51 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
proxy_1      | dockergen.1 | 2018/02/03 22:56:51 Watching docker events
proxy_1      | dockergen.1 | 2018/02/03 22:56:51 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
proxy_1      | nginx.1    | mzmbo.dev 172.20.0.3 - - [03/Feb/2018:22:56:54 +0000] "POST /wp-cron.php?doing_wp_cron=1517698614.4141230583190917968750 HTTP/1.1" 503 213 "http://mzmbo.dev/wp-cron.php?doing_wp_cron=1517698614.4141230583190917968750" "WordPress/4.9.1; http://mzmbo.dev"
proxy_1      | nginx.1    | mzmbo.dev 172.20.0.1 - - [03/Feb/2018:22:57:04 +0000] "GET / HTTP/1.1" 503 213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1      | nginx.1    | mzmbo.dev 172.20.0.1 - - [03/Feb/2018:22:57:05 +0000] "GET /robots.txt/ HTTP/1.1" 503 213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0"
```

My `.env` file looks like:

```
DOCKER_DEV_DOMAIN=mzmbo.dev
DOCKER_LOCAL_IP=192.168.1.66 # docker host's IP
PHPUNIT_TEST_DIR=mz-mindbody-api
```

And local `/etc/hosts` contains `128.0.0.1   localhost   mzmbo.dev`.

This is the `docker-compose.yml` file:

```
version: "2"

services:
  wordpress:
    image: "chriszarate/wordpress:4.9.1"
    environment:
      PHPUNIT_TEST_DIR: "/var/www/html/wp-content/plugins/mz-mindbody-api"
      WORDPRESS_ACTIVATE_PLUGINS: "mz-mindbody-api" # plugin folder relative to /wp-content/plugins/
      WORDPRESS_ACTIVATE_THEME: ""   # theme folder relative to /wp-content/themes/
      WORDPRESS_SITE_TITLE: "Wordpress Site"
      WORDPRESS_SITE_URL: "http://${DOCKER_DEV_DOMAIN}"
      XDEBUG_CONFIG: "remote_host=${DOCKER_LOCAL_IP} idekey=xdebug profiler_enable=1 profiler_output_name=%R.%t.out"
    depends_on:
      - "mysql"
    networks:
      - "front"
      - "back"
    volumes:
      - "./mz-mindbody-api:/var/www/html/wp-content/plugins/mz-mindbody-api"
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"
  proxy:
    image: "jwilder/nginx-proxy:alpine"
    ports:
      - "80:80"
    networks:
      front:
        aliases:
          - "${DOCKER_DEV_DOMAIN}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

networks:
  front: {}
  back: {}
```

I'm guessing something is configured wrong, but not sure where to look and hoping for some input. Thanks a lot.
